<script>
  import { onMount } from 'svelte'
  import { lang } from '$lib/i18n.js'

  const sections = [
    { id: 'getting-started', en: 'Getting Started', zh: '快速开始' },
    { id: 'dashboard',       en: 'Dashboard',        zh: '仪表盘' },
    { id: 'overview',        en: 'Overview',          zh: '概览' },
    { id: 'tokens',          en: 'Tokens',            zh: 'Token 用量' },
    { id: 'cost',            en: 'Cost',              zh: '费用' },
    { id: 'models',          en: 'Models',            zh: '模型' },
    { id: 'tool-calls',      en: 'Tool Calls',        zh: '工具调用' },
    { id: 'projects',        en: 'Projects',          zh: '项目' },
    { id: 'sessions',        en: 'Sessions',          zh: '会话' },
    { id: 'pricing',         en: 'Pricing',           zh: '定价' },
    { id: 'settings',        en: 'Settings',          zh: '设置' },
    { id: 'sync',            en: 'Sync',              zh: '多设备同步' },
    { id: 'cli',             en: 'CLI Reference',     zh: 'CLI 命令' },
  ]

  let activeSection = 'getting-started'

  function scrollTo(id) {
    const el = document.getElementById(id)
    if (el) {
      el.scrollIntoView({ behavior: 'smooth', block: 'start' })
    }
  }

  onMount(() => {
    const observer = new IntersectionObserver(
      (entries) => {
        for (const entry of entries) {
          if (entry.isIntersecting) {
            activeSection = entry.target.id
          }
        }
      },
      { rootMargin: '-20% 0px -70% 0px', threshold: 0 }
    )
    for (const s of sections) {
      const el = document.getElementById(s.id)
      if (el) observer.observe(el)
    }
    return () => observer.disconnect()
  })

  $: zh = $lang === 'zh'
</script>

<svelte:head>
  <title>{zh ? '文档' : 'Documentation'} — AIUsage</title>
</svelte:head>

<div class="docs-layout">

  <!-- ── Sticky TOC ─────────────────────────────────────────────────────── -->
  <aside class="toc">
    <div class="toc-header">{zh ? '目录' : 'Contents'}</div>
    <nav class="toc-nav">
      {#each sections as s}
        <!-- svelte-ignore a11y-missing-attribute -->
        <!-- svelte-ignore a11y-click-events-have-key-events -->
        <!-- svelte-ignore a11y-no-static-element-interactions -->
        <a
          class="toc-item"
          class:active={activeSection === s.id}
          on:click={() => scrollTo(s.id)}
        >{zh ? s.zh : s.en}</a>
      {/each}
    </nav>
  </aside>

  <!-- ── Content ─────────────────────────────────────────────────────────── -->
  <article class="docs-content">

    <div class="page-header">
      <h1>{zh ? 'AIUsage 文档' : 'AIUsage Documentation'}</h1>
      <p>{zh
        ? 'AIUsage 是一款 AI 工具用量统计平台，支持 Claude Code、Codex、OpenClaw、OpenCode、Hermes、Qoder、Cursor 等多种 AI 工具的 Token 和费用追踪。'
        : 'AIUsage is a local-first usage analytics platform for AI coding tools — tracking tokens, costs, sessions and more across Claude Code, Codex, OpenClaw, OpenCode, Hermes, Qoder, and Cursor.'
      }</p>
    </div>

    <!-- ── Getting Started ──────────────────────────────────────────────── -->
    <section id="getting-started">
      <h2>{zh ? '快速开始' : 'Getting Started'}</h2>

      {#if zh}
        <p>AIUsage 是一个命令行工具，内置 Web 仪表盘。安装完成后，它会解析 AI 工具生成的日志文件，并在本地数据库中追踪用量数据。</p>
        <h3>安装</h3>
        <pre><code>npm install -g @juliantanx/aiusage
# 或使用 pnpm
pnpm add -g @juliantanx/aiusage</code></pre>
        <h3>解析数据</h3>
        <p>解析 AI 工具的日志文件，写入本地数据库：</p>
        <pre><code>aiusage parse</code></pre>
        <h3>启动仪表盘</h3>
        <pre><code>aiusage serve
# 默认监听 http://localhost:3847</code></pre>
        <p>浏览器打开 <code>http://localhost:3847</code> 即可查看仪表盘。</p>
      {:else}
        <p>AIUsage is a CLI tool with a built-in web dashboard. After installation it parses log files generated by AI tools and tracks usage data in a local database.</p>
        <h3>Installation</h3>
        <pre><code>npm install -g @juliantanx/aiusage
# or with pnpm
pnpm add -g @juliantanx/aiusage</code></pre>
        <h3>Parse data</h3>
        <p>Parse log files from your AI tools into the local database:</p>
        <pre><code>aiusage parse</code></pre>
        <h3>Start the dashboard</h3>
        <pre><code>aiusage serve
# Listens on http://localhost:3847 by default</code></pre>
        <p>Open <code>http://localhost:3847</code> in your browser to view the dashboard.</p>
      {/if}

      <div class="callout info">
        <span class="callout-icon">ℹ</span>
        <span>{zh
          ? '仪表盘首页在浏览器首次加载时会自动触发一次解析。您也可以在 Settings 页面配置自动定期解析（仅在 aiusage serve 运行期间有效）。'
          : 'The dashboard home page triggers a parse automatically on first load. You can also configure automatic periodic parsing in Settings (only active while aiusage serve is running).'
        }</span>
      </div>

      {#if zh}
        <h3>后台运行（PM2）</h3>
        <p><code>aiusage serve</code> 默认在前台运行，关闭终端后服务会终止。如需在 Windows、macOS、Linux 上后台持续运行，请使用 PM2：</p>
        <pre><code>npm install -g pm2

# 一条命令启动后台服务（自动生成配置 + 启动 PM2）
aiusage pm2-start

# 设置开机自启（Windows 需以管理员身份执行输出的命令）
pm2 startup</code></pre>
        <p>常用管理命令：</p>
        <pre><code>pm2 list            # 查看运行状态
pm2 logs            # 查看日志
pm2 stop all        # 停止所有服务
pm2 restart all     # 重启所有服务
pm2 delete all      # 删除所有服务</code></pre>
      {:else}
        <h3>Running in Background (PM2)</h3>
        <p><code>aiusage serve</code> runs in the foreground and stops when you close the terminal. To keep it running in the background on Windows, macOS, and Linux, use PM2:</p>
        <pre><code>npm install -g pm2

# Start background services (generates config + starts PM2)
aiusage pm2-start

# Set auto-start on boot (Windows: run the output command as Administrator)
pm2 startup</code></pre>
        <p>Common management commands:</p>
        <pre><code>pm2 list            # View running status
pm2 logs            # View logs
pm2 stop all        # Stop all services
pm2 restart all     # Restart all services
pm2 delete all      # Remove all services</code></pre>
      {/if}
    </section>

    <!-- ── Dashboard ────────────────────────────────────────────────────── -->
    <section id="dashboard">
      <h2>{zh ? '仪表盘（首页）' : 'Dashboard (Home)'}</h2>
      {#if zh}
        <p>首页是一个实时 Token 计数器，显示所选时间范围内的累计用量，并每隔一段时间自动刷新。</p>
        <h3>界面元素</h3>
        <ul>
          <li><strong>实时计数器</strong>：显示总 Token 数，支持动画计数效果。</li>
          <li><strong>子统计</strong>：分别展示输入、输出和缓存 Token。</li>
          <li><strong>费用 / 会话 / 活跃天数</strong>：三个辅助统计卡片。</li>
          <li><strong>Token 构成条</strong>：按比例显示输入、输出、缓存读写的分布。</li>
          <li><strong>刷新进度条</strong>：显示下次自动刷新的倒计时。</li>
        </ul>
        <h3>⚙ 显示配置</h3>
        <p>点击右上角的 ⚙ 按钮可打开显示配置面板，支持：</p>
        <ul>
          <li><strong>时间范围</strong>：今天 / 本周 / 本月 / 近 30 天 / 全部。</li>
          <li><strong>数字格式</strong>：精确（1,234,567）或简短（1.2M）。</li>
        </ul>
        <p>刷新间隔在「设置」页面的「仪表盘轮询间隔」字段中配置（毫秒）。</p>
      {:else}
        <p>The home page is a live token counter showing cumulative usage for the selected time range, auto-refreshing at a configurable interval.</p>
        <h3>UI Elements</h3>
        <ul>
          <li><strong>Live counter</strong> — Total token count with an animated count-up effect.</li>
          <li><strong>Sub-stats</strong> — Input, output, and cache tokens shown separately.</li>
          <li><strong>Cost / Sessions / Active Days</strong> — Three secondary stat cards.</li>
          <li><strong>Token composition bar</strong> — Proportional breakdown of input, output, cache read/write.</li>
          <li><strong>Refresh progress bar</strong> — Countdown until next auto-refresh.</li>
        </ul>
        <h3>⚙ Display Config</h3>
        <p>Click the ⚙ button to open the display config panel where you can set:</p>
        <ul>
          <li><strong>Time range</strong> — Today / This Week / This Month / Last 30d / All Time.</li>
          <li><strong>Number format</strong> — Exact (1,234,567) or abbreviated (1.2M).</li>
        </ul>
        <p>The refresh interval is configured under Settings → Dashboard Poll Interval (milliseconds).</p>
      {/if}
    </section>

    <!-- ── Overview ─────────────────────────────────────────────────────── -->
    <section id="overview">
      <h2>{zh ? '概览' : 'Overview'}</h2>
      {#if zh}
        <p>概览页展示带筛选条件的聚合统计摘要，是了解整体用量的起点。</p>
        <h3>统计卡片</h3>
        <ul>
          <li><strong>总 Token</strong>：所有类型 Token 的合计。</li>
          <li><strong>总费用</strong>：基于定价表计算的估算费用。</li>
          <li><strong>活跃天数</strong>：有记录的天数。</li>
          <li><strong>会话数</strong>：独立会话的总数。</li>
        </ul>
        <h3>Token 明细</h3>
        <p>在卡片下方展示输入、输出、缓存读取、缓存写入的分项数据。</p>
        <h3>按 AI 助手统计</h3>
        <p>按使用的 AI 工具（claude-code、codex 等）分组，显示各工具的 Token 数和费用。</p>
        <h3>常用工具调用</h3>
        <p>列出调用次数最多的工具（如 Bash、Read、Edit 等）。</p>
      {:else}
        <p>The Overview page shows aggregated usage stats with filters — your go-to starting point for understanding overall usage.</p>
        <h3>Stat Cards</h3>
        <ul>
          <li><strong>Total Tokens</strong> — Sum of all token types.</li>
          <li><strong>Total Cost</strong> — Estimated cost based on the pricing table.</li>
          <li><strong>Active Days</strong> — Number of days with recorded usage.</li>
          <li><strong>Sessions</strong> — Total number of distinct sessions.</li>
        </ul>
        <h3>Token Breakdown</h3>
        <p>Below the cards: input, output, cache read, and cache write token counts shown individually.</p>
        <h3>By AI Assistant</h3>
        <p>Usage grouped by AI tool (claude-code, codex, etc.) showing tokens and cost per tool.</p>
        <h3>Top Tool Calls</h3>
        <p>The most-called tool names (e.g. Bash, Read, Edit) ranked by invocation count.</p>
      {/if}

      <div class="callout tip">
        <span class="callout-icon">✦</span>
        <span>{zh
          ? '使用页面顶部的筛选栏可以按日期范围、设备、AI 助手进行过滤，所有数据页面均支持这些筛选条件。'
          : 'Use the filter bar at the top to narrow by date range, device, and AI assistant — all data pages share these filters.'
        }</span>
      </div>
    </section>

    <!-- ── Tokens ────────────────────────────────────────────────────────── -->
    <section id="tokens">
      <h2>{zh ? 'Token 用量' : 'Tokens'}</h2>
      {#if zh}
        <p>Token 页面以每日图表和明细表格的形式展示 Token 消耗趋势。</p>
        <h3>每日柱状图</h3>
        <p>每组柱子展示同一天内的各类 Token（输入、输出、缓存读取、缓存写入、思考 Token），悬停可查看具体数值。</p>
        <h3>明细表格</h3>
        <p>表格列出每天各类型的 Token 数量及合计，支持横向滚动查看较长时间范围的数据。</p>
        <h3>Token 类型说明</h3>
        <ul>
          <li><strong>输入</strong>：发送给模型的提示 Token。</li>
          <li><strong>输出</strong>：模型生成的回复 Token。</li>
          <li><strong>缓存读取</strong>：从缓存中命中并读取的 Token（计费更低）。</li>
          <li><strong>缓存写入</strong>：写入缓存的 Token。</li>
          <li><strong>思考</strong>：扩展思考（Extended Thinking）功能使用的 Token。</li>
        </ul>
      {:else}
        <p>The Tokens page visualizes daily token consumption with a bar chart and a detail table.</p>
        <h3>Daily Bar Chart</h3>
        <p>Each bar group shows the token types for one day (input, output, cache read, cache write, thinking). Hover over bars to see exact counts.</p>
        <h3>Detail Table</h3>
        <p>A table below lists per-day counts for each token type plus a daily total. Scroll horizontally for longer date ranges.</p>
        <h3>Token Types</h3>
        <ul>
          <li><strong>Input</strong> — Prompt tokens sent to the model.</li>
          <li><strong>Output</strong> — Tokens generated by the model.</li>
          <li><strong>Cache Read</strong> — Tokens read from the cache (billed at a lower rate).</li>
          <li><strong>Cache Write</strong> — Tokens written to the cache.</li>
          <li><strong>Thinking</strong> — Tokens used by Extended Thinking mode.</li>
        </ul>
      {/if}
    </section>

    <!-- ── Cost ──────────────────────────────────────────────────────────── -->
    <section id="cost">
      <h2>{zh ? '费用' : 'Cost'}</h2>
      {#if zh}
        <p>费用页面展示每日费用走势及按 AI 助手、模型的费用分布。</p>
        <h3>总费用卡片</h3>
        <p>显示筛选时间范围内的总估算费用。</p>
        <h3>每日费用图</h3>
        <p>柱状图展示每天的费用，悬停可查看当日金额。</p>
        <h3>按 AI 助手分布</h3>
        <p>不同工具（Claude Code、Codex 等）的费用排名。</p>
        <h3>按模型分布</h3>
        <p>不同模型（claude-sonnet-4-5、gpt-4o 等）的费用排名。</p>
        <div class="callout warn">
          <span class="callout-icon">△</span>
          <span>费用为估算值，基于「定价」页面中配置的每百万 Token 单价计算。如发现费用偏差，请在「定价」页面检查并修正价格。</span>
        </div>
      {:else}
        <p>The Cost page shows daily spending trends and a breakdown by AI assistant and model.</p>
        <h3>Total Cost Card</h3>
        <p>Displays the total estimated cost for the selected date range.</p>
        <h3>Daily Cost Chart</h3>
        <p>A bar chart showing per-day costs. Hover to view exact amounts.</p>
        <h3>By AI Assistant</h3>
        <p>Ranked list of costs per tool (Claude Code, Codex, etc.).</p>
        <h3>By Model</h3>
        <p>Ranked list of costs per model (e.g. claude-sonnet-4-5, gpt-4o).</p>
        <div class="callout warn">
          <span class="callout-icon">△</span>
          <span>Costs are estimates calculated using per-million-token prices from the Pricing page. If costs look wrong, review and update prices there.</span>
        </div>
      {/if}
    </section>

    <!-- ── Models ────────────────────────────────────────────────────────── -->
    <section id="models">
      <h2>{zh ? '模型' : 'Models'}</h2>
      {#if zh}
        <p>模型页面展示各 AI 模型的使用量排名，帮助了解哪些模型被频繁调用。</p>
        <h3>表格列</h3>
        <ul>
          <li><strong>模型</strong>：模型 ID（如 claude-sonnet-4-6）。</li>
          <li><strong>提供商</strong>：模型的服务提供商（Anthropic、OpenAI 等）。</li>
          <li><strong>调用次数</strong>：该模型被调用的次数。</li>
          <li><strong>Token</strong>：该模型消耗的 Token 总量。</li>
          <li><strong>占比</strong>：该模型在所有 Token 中的占比（含进度条）。</li>
        </ul>
      {:else}
        <p>The Models page ranks AI model usage to show which models are used most.</p>
        <h3>Table Columns</h3>
        <ul>
          <li><strong>Model</strong> — Model ID (e.g. claude-sonnet-4-6).</li>
          <li><strong>Provider</strong> — Service provider (Anthropic, OpenAI, etc.).</li>
          <li><strong>Calls</strong> — Number of times this model was invoked.</li>
          <li><strong>Tokens</strong> — Total tokens consumed by this model.</li>
          <li><strong>Share</strong> — Percentage of total tokens (with a progress bar).</li>
        </ul>
      {/if}
    </section>

    <!-- ── Tool Calls ─────────────────────────────────────────────────────── -->
    <section id="tool-calls">
      <h2>{zh ? '工具调用' : 'Tool Calls'}</h2>
      {#if zh}
        <p>工具调用页面展示 AI 助手在会话中调用各工具的频次排名。</p>
        <p>工具调用是 AI 助手执行的具体操作，例如 <code>Bash</code>（运行命令）、<code>Read</code>（读取文件）、<code>Edit</code>（修改文件）等。通过此页面可以了解 AI 助手最常执行哪类操作。</p>
        <h3>排名列</h3>
        <ul>
          <li><strong>排名</strong>：按调用次数从高到低排列。</li>
          <li><strong>工具名</strong>：工具的唯一标识名称。</li>
          <li><strong>相对占比条</strong>：相对于最多调用工具的比例条。</li>
          <li><strong>调用次数</strong>：绝对调用数量。</li>
          <li><strong>占比</strong>：占所有工具调用的百分比。</li>
        </ul>
      {:else}
        <p>The Tool Calls page ranks how frequently each tool was invoked by AI assistants in sessions.</p>
        <p>Tool calls are specific actions performed by the AI — e.g. <code>Bash</code> (run commands), <code>Read</code> (read files), <code>Edit</code> (modify files). Use this page to understand which operations the AI performs most.</p>
        <h3>Ranking Columns</h3>
        <ul>
          <li><strong>Rank</strong> — Sorted by invocation count descending.</li>
          <li><strong>Tool name</strong> — The tool's unique identifier.</li>
          <li><strong>Relative bar</strong> — Width proportional to the top-ranked tool.</li>
          <li><strong>Count</strong> — Absolute invocation count.</li>
          <li><strong>Share</strong> — Percentage of all tool calls.</li>
        </ul>
      {/if}
    </section>

    <!-- ── Projects ──────────────────────────────────────────────────────── -->
    <section id="projects">
      <h2>{zh ? '项目' : 'Projects'}</h2>
      {#if zh}
        <p>项目页面按项目目录展示 Token 用量和费用排名，帮助了解哪些代码库消耗了最多资源。</p>
        <p>项目名称来自 AI 工具日志中记录的工作目录路径。Claude Code 会自动记录每次会话对应的项目路径。</p>
        <h3>排名列</h3>
        <ul>
          <li><strong>排名</strong>：按 Token 用量从高到低排列。</li>
          <li><strong>项目名</strong>：工作目录的名称或路径。</li>
          <li><strong>相对占比条</strong>：Token 用量的相对比例。</li>
          <li><strong>Token</strong>：该项目消耗的 Token 总量。</li>
          <li><strong>费用</strong>：该项目的估算费用。</li>
          <li><strong>占比</strong>：占总 Token 的百分比。</li>
        </ul>
      {:else}
        <p>The Projects page ranks token usage and cost by project directory to show which codebases consume the most resources.</p>
        <p>Project names come from the working directory path recorded in AI tool logs. Claude Code automatically records the project path for each session.</p>
        <h3>Ranking Columns</h3>
        <ul>
          <li><strong>Rank</strong> — Sorted by token count descending.</li>
          <li><strong>Project</strong> — Working directory name or path.</li>
          <li><strong>Relative bar</strong> — Proportional width showing relative token usage.</li>
          <li><strong>Tokens</strong> — Total tokens consumed for this project.</li>
          <li><strong>Cost</strong> — Estimated cost for this project.</li>
          <li><strong>Share</strong> — Percentage of total tokens.</li>
        </ul>
      {/if}
    </section>

    <!-- ── Sessions ──────────────────────────────────────────────────────── -->
    <section id="sessions">
      <h2>{zh ? '会话' : 'Sessions'}</h2>
      {#if zh}
        <p>会话页面展示每一条会话记录的详细日志，每页显示 50 条，支持翻页。</p>
        <h3>表格列</h3>
        <ul>
          <li><strong>时间</strong>：会话发生的时间戳。</li>
          <li><strong>工具</strong>：使用的 AI 助手（如 claude-code）。</li>
          <li><strong>模型</strong>：本次会话使用的模型。</li>
          <li><strong>输入</strong>：输入 Token 数量。</li>
          <li><strong>输出</strong>：输出 Token 数量。</li>
          <li><strong>费用</strong>：本次会话的估算费用。</li>
        </ul>
        <h3>翻页</h3>
        <p>使用页面底部的「上一页 / 下一页」按钮切换页码，每页固定显示 50 条记录。</p>
      {:else}
        <p>The Sessions page shows a detailed log of every recorded session, paginated at 50 per page.</p>
        <h3>Table Columns</h3>
        <ul>
          <li><strong>Time</strong> — Timestamp of the session.</li>
          <li><strong>Tool</strong> — AI assistant used (e.g. claude-code).</li>
          <li><strong>Model</strong> — Model used in this session.</li>
          <li><strong>Input</strong> — Input token count.</li>
          <li><strong>Output</strong> — Output token count.</li>
          <li><strong>Cost</strong> — Estimated cost for this session.</li>
        </ul>
        <h3>Pagination</h3>
        <p>Use the Previous / Next buttons at the bottom to navigate pages. Each page shows 50 records.</p>
      {/if}
    </section>

    <!-- ── Pricing ───────────────────────────────────────────────────────── -->
    <section id="pricing">
      <h2>{zh ? '定价' : 'Pricing'}</h2>
      {#if zh}
        <p>定价页面用于管理各模型的每百万 Token 单价，用于计算整个仪表盘的费用估算。</p>
        <h3>定价卡片</h3>
        <p>每个模型显示一张卡片，包含：</p>
        <ul>
          <li><strong>模型名</strong>：模型 ID。</li>
          <li><strong>输入 / 输出</strong>：每百万 Token 的主要费率（美元）。</li>
          <li><strong>缓存读取 / 缓存写入 / 思考</strong>：次要费率。</li>
          <li><strong>状态标签</strong>：默认（内置）/ 自定义（手动覆盖）/ 前缀匹配 / 无定价。</li>
        </ul>
        <h3>编辑定价</h3>
        <p>点击「编辑」按钮进入编辑模式，修改后点击「保存」。自定义价格会覆盖内置默认值。</p>
        <h3>重置</h3>
        <p>对于已自定义的模型，点击「重置」可恢复到内置默认价格。</p>
        <h3>重新计算费用</h3>
        <p>修改价格后，点击「重新计算费用」按钮，系统会对所有历史会话重新计算费用。</p>
        <div class="callout warn">
          <span class="callout-icon">△</span>
          <span>重新计算费用是不可逆操作，会更新数据库中所有历史会话的费用字段。</span>
        </div>
      {:else}
        <p>The Pricing page manages per-million-token rates for each model used across the dashboard's cost estimates.</p>
        <h3>Pricing Cards</h3>
        <p>Each model appears as a card showing:</p>
        <ul>
          <li><strong>Model name</strong> — Model identifier.</li>
          <li><strong>Input / Output</strong> — Primary rates per million tokens (USD).</li>
          <li><strong>Cache Read / Write / Thinking</strong> — Secondary rates.</li>
          <li><strong>Status badge</strong> — Default (built-in) / Custom (manual override) / Prefix match / No pricing.</li>
        </ul>
        <h3>Editing Prices</h3>
        <p>Click Edit on a card to enter edit mode. Save to apply. Custom prices override the built-in defaults.</p>
        <h3>Reset</h3>
        <p>For overridden models, click Reset to restore the built-in default price.</p>
        <h3>Recalculate Costs</h3>
        <p>After changing prices, click "Recalculate Costs" to recompute costs for all historical sessions.</p>
        <div class="callout warn">
          <span class="callout-icon">△</span>
          <span>Recalculation is irreversible and updates the cost field for all sessions in the database.</span>
        </div>
      {/if}
    </section>

    <!-- ── Settings ──────────────────────────────────────────────────────── -->
    <section id="settings">
      <h2>{zh ? '设置' : 'Settings'}</h2>
      {#if zh}
        <p>设置页面按模块分区，每个区域独立保存。</p>
        <h3>通用</h3>
        <table class="docs-table">
          <thead><tr><th>字段</th><th>说明</th></tr></thead>
          <tbody>
            <tr><td>设备别名</td><td>可选的当前设备名称，留空则使用主机名。用于多设备场景下区分数据来源。</td></tr>
            <tr><td>每周起始日</td><td>「本周」时间范围的起始天（周日或周一 ISO）。</td></tr>
            <tr><td>仪表盘轮询间隔</td><td>首页自动刷新的间隔（毫秒，默认 30000）。</td></tr>
            <tr><td>自动解析间隔</td><td>后台自动触发解析的间隔（毫秒）。设为 0 或留空则禁用。</td></tr>
          </tbody>
        </table>
        <h3>数据源</h3>
        <p>为每种 AI 工具指定自定义日志目录路径。留空则使用各工具的默认路径：</p>
        <ul>
          <li><strong>Claude Code</strong>：<code>~/.claude/projects</code></li>
          <li><strong>Codex</strong>：<code>~/.codex/sessions</code></li>
          <li><strong>OpenClaw</strong>：<code>~/.openclaw/agents</code></li>
          <li><strong>OpenCode</strong>：平台相关的 SQLite 数据库路径</li>
          <li><strong>Hermes</strong>：<code>~/.hermes/state.db</code></li>
          <li><strong>Qoder（会话日志）</strong>：<code>~/.qoder/logs/sessions</code></li>
          <li><strong>Qoder（SQLite）</strong>：平台相关的 <code>local.db</code> 路径</li>
          <li><strong>Cursor</strong>：平台相关的 <code>state.vscdb</code> 路径</li>
        </ul>
        <h3>同步</h3>
        <p>见下方「多设备同步」章节。</p>
        <h3>数据管理</h3>
        <p><strong>本地数据保留天数</strong>：超过此天数的旧数据将被清理。设为 0 或留空则永久保留。</p>
      {:else}
        <p>The Settings page is divided into sections, each saved independently.</p>
        <h3>General</h3>
        <table class="docs-table">
          <thead><tr><th>Field</th><th>Description</th></tr></thead>
          <tbody>
            <tr><td>Device Alias</td><td>Optional name for this device. Defaults to hostname. Used to distinguish data sources in multi-device setups.</td></tr>
            <tr><td>Week Starts On</td><td>Starting day for the "This Week" date range (Sunday or Monday ISO).</td></tr>
            <tr><td>Dashboard Poll Interval</td><td>Auto-refresh interval for the home page in milliseconds (default: 30000).</td></tr>
            <tr><td>Auto-Parse Interval</td><td>Background parse interval in milliseconds. Set to 0 or leave empty to disable.</td></tr>
          </tbody>
        </table>
        <h3>Sources</h3>
        <p>Specify custom log directory paths for each AI tool. Leave blank for defaults:</p>
        <ul>
          <li><strong>Claude Code</strong> — <code>~/.claude/projects</code></li>
          <li><strong>Codex</strong> — <code>~/.codex/sessions</code></li>
          <li><strong>OpenClaw</strong> — <code>~/.openclaw/agents</code></li>
          <li><strong>OpenCode</strong> — platform-specific SQLite database path</li>
          <li><strong>Hermes</strong> — <code>~/.hermes/state.db</code></li>
          <li><strong>Qoder (sessions)</strong> — <code>~/.qoder/logs/sessions</code></li>
          <li><strong>Qoder (SQLite)</strong> — platform-specific <code>local.db</code> path</li>
          <li><strong>Cursor</strong> — platform-specific <code>state.vscdb</code> path</li>
        </ul>
        <h3>Sync</h3>
        <p>See the Sync section below.</p>
        <h3>Data</h3>
        <p><strong>Local Data Retention (days)</strong> — Data older than this many days will be cleaned up. Set to 0 or leave empty to keep forever.</p>
      {/if}
    </section>

    <!-- ── Sync ──────────────────────────────────────────────────────────── -->
    <section id="sync">
      <h2>{zh ? '多设备同步' : 'Sync'}</h2>
      {#if zh}
        <p>同步功能将本设备的数据推送到远程存储，并从远程拉取其他设备的数据，实现多台设备之间的用量统计共享。</p>
        <h3>支持的后端</h3>
        <ul>
          <li><strong>GitHub</strong>：推送到 GitHub 仓库。</li>
          <li><strong>S3 / 兼容存储</strong>：推送到 Amazon S3 或任何 S3 兼容存储（如 Cloudflare R2、MinIO）。</li>
        </ul>
        <h3>配置 GitHub 同步</h3>
        <ol>
          <li>在设置页面的「同步」区域选择后端为 <strong>GitHub</strong>。</li>
          <li>填写「仓库」字段（格式：<code>owner/repo</code>）。</li>
          <li>填写 GitHub Token（具有仓库写入权限的 Personal Access Token）。</li>
          <li>点击「保存」。</li>
        </ol>
        <h3>配置 S3 同步</h3>
        <ol>
          <li>选择后端为 <strong>S3 / Compatible</strong>。</li>
          <li>填写存储桶名称、Endpoint、Region、前缀（可选）。</li>
          <li>填写 <strong>Access Key ID</strong> 字段。</li>
          <li>填写 <strong>Secret Access Key</strong> 字段。</li>
          <li>点击「保存」。</li>
        </ol>
        <h3>触发同步</h3>
        <p>点击侧边栏底部的 <strong>⇅ 同步</strong> 按钮手动触发一次同步，或使用 CLI：</p>
        <pre><code>aiusage sync</code></pre>
      {:else}
        <p>Sync pushes this device's data to remote storage and pulls other devices' data from it, sharing usage stats across machines.</p>
        <h3>Supported Backends</h3>
        <ul>
          <li><strong>GitHub</strong> — Push to a GitHub repository.</li>
          <li><strong>S3 / Compatible</strong> — Push to Amazon S3 or any S3-compatible storage (Cloudflare R2, MinIO, etc.).</li>
        </ul>
        <h3>Configure GitHub Sync</h3>
        <ol>
          <li>In Settings → Sync, set Backend to <strong>GitHub</strong>.</li>
          <li>Fill in the Repository field (format: <code>owner/repo</code>).</li>
          <li>Enter your GitHub Token — a Personal Access Token with repo write permission.</li>
          <li>Click Save.</li>
        </ol>
        <h3>Configure S3 Sync</h3>
        <ol>
          <li>Set Backend to <strong>S3 / Compatible</strong>.</li>
          <li>Fill in bucket, endpoint, region, and optional prefix.</li>
          <li>Enter the <strong>Access Key ID</strong>.</li>
          <li>Enter the <strong>Secret Access Key</strong>.</li>
          <li>Click Save.</li>
        </ol>
        <h3>Triggering a Sync</h3>
        <p>Click the <strong>⇅ Sync</strong> button in the sidebar footer, or use the CLI:</p>
        <pre><code>aiusage sync</code></pre>
      {/if}
    </section>

    <!-- ── CLI ───────────────────────────────────────────────────────────── -->
    <section id="cli">
      <h2>{zh ? 'CLI 命令参考' : 'CLI Reference'}</h2>
      {#if zh}
        <p>所有 CLI 命令均通过 <code>aiusage &lt;command&gt;</code> 调用。不带子命令时等同于 <code>aiusage summary</code>。</p>

        <h3><code>parse</code> — 解析日志</h3>
        <p>从自动发现的数据来源路径导入本地新追加的会话数据。</p>
        <table class="docs-table">
          <thead><tr><th>选项</th><th>说明</th></tr></thead>
          <tbody>
            <tr><td><code>--tool &lt;tool&gt;</code></td><td>只解析指定工具：<code>claude-code</code>、<code>codex</code>、<code>openclaw</code>、<code>opencode</code>、<code>hermes</code>、<code>qoder</code>、<code>cursor</code></td></tr>
            <tr><td><code>--progress</code></td><td>在 stderr 显示实时进度条（仅 TTY 环境，管道/CI 下自动静默）</td></tr>
          </tbody>
        </table>
        <pre><code>aiusage parse                        # 解析所有工具
aiusage parse --tool claude-code     # 只解析 Claude Code
aiusage parse --progress             # 显示进度条</code></pre>

        <h3><code>serve</code> — 启动仪表盘</h3>
        <table class="docs-table">
          <thead><tr><th>选项</th><th>说明</th><th>默认值</th></tr></thead>
          <tbody>
            <tr><td><code>-p, --port &lt;port&gt;</code></td><td>端口号</td><td><code>3847</code></td></tr>
          </tbody>
        </table>
        <pre><code>aiusage serve             # 使用 3847 端口
aiusage serve -p 8080     # 使用 8080 端口</code></pre>

        <h3><code>summary</code> — 终端摘要</h3>
        <table class="docs-table">
          <thead><tr><th>选项</th><th>说明</th></tr></thead>
          <tbody>
            <tr><td><code>--device &lt;id&gt;</code></td><td>按设备实例 ID 筛选</td></tr>
            <tr><td><code>--tool &lt;tool&gt;</code></td><td>按工具类型筛选</td></tr>
          </tbody>
        </table>

        <h3><code>export</code> — 导出数据</h3>
        <table class="docs-table">
          <thead><tr><th>选项</th><th>说明</th><th>必填</th></tr></thead>
          <tbody>
            <tr><td><code>--format &lt;f&gt;</code></td><td>输出格式：<code>csv</code>、<code>json</code>、<code>ndjson</code></td><td>是</td></tr>
            <tr><td><code>-o, --output &lt;f&gt;</code></td><td>输出文件路径（默认 stdout）</td><td>否</td></tr>
          </tbody>
        </table>

        <h3><code>clean</code> — 清理旧数据</h3>
        <table class="docs-table">
          <thead><tr><th>选项</th><th>说明</th><th>默认值</th></tr></thead>
          <tbody>
            <tr><td><code>--before &lt;dur&gt;</code></td><td>删除此时间之前的数据（如 <code>30d</code>、<code>180d</code>）</td><td><code>180d</code></td></tr>
          </tbody>
        </table>

        <h3><code>reset</code> — 重置所有数据</h3>
        <p>删除所有已解析的记录、工具调用、同步数据和水位线。原始日志文件不受影响。用于从头重新导入。</p>
        <table class="docs-table">
          <thead><tr><th>选项</th><th>说明</th></tr></thead>
          <tbody>
            <tr><td><code>--yes</code></td><td>跳过确认提示（必须指定才会执行）</td></tr>
          </tbody>
        </table>
        <pre><code>aiusage reset --yes    # 清空后执行 aiusage parse 重新导入</code></pre>

        <h3>其他命令</h3>
        <table class="docs-table">
          <thead><tr><th>命令</th><th>说明</th><th>选项</th></tr></thead>
          <tbody>
            <tr><td><code>status</code></td><td>显示版本号、设备名称、数据库路径、schema 版本、表和视图数量、记录数、数据库大小及同步状态</td><td>—</td></tr>
            <tr><td><code>sync</code></td><td>与远程后端双向同步数据</td><td>—</td></tr>
            <tr><td><code>recalc</code></td><td>按最新定价重新计算费用</td><td>—</td></tr>
            <tr><td><code>init</code></td><td>配置同步后端</td><td><code>--backend</code>、<code>--repo</code>、<code>--token</code>、<code>--bucket</code>、<code>--endpoint</code> 等</td></tr>
          </tbody>
        </table>
      {:else}
        <p>All CLI commands are invoked as <code>aiusage &lt;command&gt;</code>. Running without a subcommand is equivalent to <code>aiusage summary</code>.</p>

        <h3><code>parse</code> — Parse Logs</h3>
        <p>Import newly appended local session data from discovered source paths.</p>
        <table class="docs-table">
          <thead><tr><th>Option</th><th>Description</th></tr></thead>
          <tbody>
            <tr><td><code>--tool &lt;tool&gt;</code></td><td>Only parse a specific tool: <code>claude-code</code>, <code>codex</code>, <code>openclaw</code>, <code>opencode</code>, <code>hermes</code>, <code>qoder</code>, <code>cursor</code></td></tr>
            <tr><td><code>--progress</code></td><td>Show real-time progress bar on stderr (TTY only, silent in pipes/CI)</td></tr>
          </tbody>
        </table>
        <pre><code>aiusage parse                        # Parse all tools
aiusage parse --tool claude-code     # Only parse Claude Code
aiusage parse --progress             # Show progress bar</code></pre>

        <h3><code>serve</code> — Start Dashboard</h3>
        <table class="docs-table">
          <thead><tr><th>Option</th><th>Description</th><th>Default</th></tr></thead>
          <tbody>
            <tr><td><code>-p, --port &lt;port&gt;</code></td><td>Port number</td><td><code>3847</code></td></tr>
          </tbody>
        </table>
        <pre><code>aiusage serve             # Start on port 3847
aiusage serve -p 8080     # Start on port 8080</code></pre>

        <h3><code>summary</code> — Terminal Summary</h3>
        <table class="docs-table">
          <thead><tr><th>Option</th><th>Description</th></tr></thead>
          <tbody>
            <tr><td><code>--device &lt;id&gt;</code></td><td>Filter by device instance ID</td></tr>
            <tr><td><code>--tool &lt;tool&gt;</code></td><td>Filter by tool type</td></tr>
          </tbody>
        </table>

        <h3><code>export</code> — Export Data</h3>
        <table class="docs-table">
          <thead><tr><th>Option</th><th>Description</th><th>Required</th></tr></thead>
          <tbody>
            <tr><td><code>--format &lt;f&gt;</code></td><td>Output format: <code>csv</code>, <code>json</code>, <code>ndjson</code></td><td>Yes</td></tr>
            <tr><td><code>-o, --output &lt;f&gt;</code></td><td>Output file path (default: stdout)</td><td>No</td></tr>
          </tbody>
        </table>

        <h3><code>clean</code> — Clean Old Data</h3>
        <table class="docs-table">
          <thead><tr><th>Option</th><th>Description</th><th>Default</th></tr></thead>
          <tbody>
            <tr><td><code>--before &lt;dur&gt;</code></td><td>Delete data older than this (e.g. <code>30d</code>, <code>180d</code>)</td><td><code>180d</code></td></tr>
          </tbody>
        </table>

        <h3><code>reset</code> — Reset All Data</h3>
        <p>Delete all parsed records, tool calls, synced data, and the parse watermark. Source log files are not affected. Use this to re-import everything from scratch.</p>
        <table class="docs-table">
          <thead><tr><th>Option</th><th>Description</th></tr></thead>
          <tbody>
            <tr><td><code>--yes</code></td><td>Skip confirmation prompt (required to execute)</td></tr>
          </tbody>
        </table>
        <pre><code>aiusage reset --yes    # Wipe all, then run aiusage parse to re-import</code></pre>

        <h3>Other Commands</h3>
        <table class="docs-table">
          <thead><tr><th>Command</th><th>Description</th><th>Options</th></tr></thead>
          <tbody>
            <tr><td><code>status</code></td><td>Show version, device name, DB path, schema version, table/view counts, record count, DB size, and sync status</td><td>—</td></tr>
            <tr><td><code>sync</code></td><td>Push and pull data with remote backend</td><td>—</td></tr>
            <tr><td><code>recalc</code></td><td>Recalculate costs with latest pricing</td><td>—</td></tr>
            <tr><td><code>init</code></td><td>Configure a sync backend</td><td><code>--backend</code>, <code>--repo</code>, <code>--token</code>, <code>--bucket</code>, <code>--endpoint</code>, etc.</td></tr>
          </tbody>
        </table>
      {/if}
    </section>

  </article>
</div>

<style>
  /* ── Layout ───────────────────────────────────────────────────────────── */
  .docs-layout {
    display: grid;
    grid-template-columns: 200px 1fr;
    gap: 3rem;
    align-items: start;
  }

  /* ── TOC ──────────────────────────────────────────────────────────────── */
  .toc {
    position: sticky;
    top: 1.5rem;
    max-height: calc(100vh - 3rem);
    overflow-y: auto;
    scrollbar-width: thin;
  }
  /* On mobile (<=800px) the sticky header is ~52px tall; add clearance */
  @media (max-width: 800px) and (min-width: 701px) {
    .toc {
      top: 4.5rem;
      max-height: calc(100vh - 6rem);
    }
  }

  .toc-header {
    font-family: var(--mono);
    font-size: 0.625rem;
    font-weight: 550;
    letter-spacing: 0.06em;
    text-transform: uppercase;
    color: var(--text-muted);
    margin-bottom: 0.6rem;
    padding-bottom: 0.5rem;
    border-bottom: 1px solid var(--border-subtle);
  }

  .toc-nav {
    display: flex;
    flex-direction: column;
    gap: 0.05rem;
  }

  .toc-item {
    display: block;
    font-size: 0.78rem;
    color: var(--text-secondary);
    padding: 0.28rem 0.6rem;
    border-radius: 4px;
    cursor: pointer;
    transition: color 0.2s, background 0.2s;
    text-decoration: none;
  }
  .toc-item:hover {
    color: var(--text);
    background: var(--hover);
  }
  .toc-item.active {
    color: var(--accent);
    background: var(--accent-dim);
    font-weight: 600;
  }

  /* ── Content ──────────────────────────────────────────────────────────── */
  .docs-content {
    min-width: 0;
    max-width: 72ch;
  }

  .docs-content :global(.page-header) {
    margin-bottom: 2.5rem;
    padding-bottom: 1.5rem;
    border-bottom: 1px solid var(--border-subtle);
  }

  section {
    margin-bottom: 3rem;
    padding-top: 0.5rem;
  }

  section h2 {
    font-family: var(--mono);
    font-size: 1rem;
    font-weight: 700;
    color: var(--text);
    letter-spacing: -0.02em;
    margin-bottom: 0.9rem;
    padding-bottom: 0.6rem;
    border-bottom: 1px solid var(--border-subtle);
  }

  section h3 {
    font-family: var(--mono);
    font-size: 0.625rem;
    font-weight: 550;
    color: var(--text-secondary);
    letter-spacing: 0.06em;
    margin: 1.2rem 0 0.5rem;
    text-transform: uppercase;
  }

  section p {
    font-size: 0.86rem;
    color: var(--text-secondary);
    line-height: 1.65;
    margin-bottom: 0.75rem;
  }

  section ul, section ol {
    padding-left: 1.4rem;
    margin-bottom: 0.75rem;
  }

  section li {
    font-size: 0.86rem;
    color: var(--text-secondary);
    line-height: 1.65;
    margin-bottom: 0.3rem;
  }

  section strong {
    color: var(--text);
    font-weight: 600;
  }

  section code {
    font-family: var(--mono);
    font-size: 0.78rem;
    background: var(--raised);
    border-radius: 4px;
    padding: 0.1em 0.4em;
    color: var(--accent);
  }

  pre {
    background: var(--raised);
    border: 1px solid var(--border-subtle);
    border-radius: 6px;
    padding: 1rem 1.1rem;
    overflow-x: auto;
    margin: 0.75rem 0;
  }
  pre code {
    background: none;
    border: none;
    padding: 0;
    font-size: 0.8rem;
    color: var(--text);
  }

  /* ── Callouts ─────────────────────────────────────────────────────────── */
  .callout {
    display: flex;
    gap: 0.65rem;
    align-items: flex-start;
    padding: 0.75rem 1rem;
    border-radius: 8px;
    margin: 1rem 0;
    font-size: 0.84rem;
    line-height: 1.55;
    border: none;
    border-left: 3px solid;
    background: var(--raised);
  }
  .callout-icon {
    font-size: 0.8rem;
    flex-shrink: 0;
    margin-top: 0.08rem;
  }
  .callout.info {
    border-left-color: var(--blue);
    color: var(--blue);
  }
  .callout.tip {
    border-left-color: var(--accent);
    color: var(--accent);
  }
  .callout.warn {
    border-left-color: var(--rose);
    color: var(--rose);
  }

  /* ── Docs table ───────────────────────────────────────────────────────── */
  .docs-table {
    width: 100%;
    border-collapse: collapse;
    margin: 0.75rem 0;
    font-size: 0.84rem;
  }
  .docs-table th {
    font-family: var(--mono);
    font-size: 0.625rem;
    font-weight: 550;
    text-transform: uppercase;
    letter-spacing: 0.06em;
    color: var(--text-muted);
    text-align: left;
    padding: 0.5rem 0.75rem;
    border-bottom: 1px solid var(--border-medium);
    background: var(--raised);
  }
  .docs-table td {
    padding: 0.55rem 0.75rem;
    border-bottom: 1px solid var(--border-subtle);
    color: var(--text-secondary);
    vertical-align: top;
  }
  .docs-table tr:hover td {
    background: var(--hover);
  }
  .docs-table td:first-child {
    font-family: var(--mono);
    font-size: 0.78rem;
    color: var(--text);
    white-space: nowrap;
  }

  /* ── Responsive ───────────────────────────────────────────────────────── */
  @media (max-width: 800px) {
    .docs-layout {
      grid-template-columns: 1fr;
    }
    .toc {
      position: static;
      max-height: none;
      display: flex;
      flex-wrap: wrap;
      gap: 0.35rem;
    }
    .toc-header { width: 100%; }
    .toc-item {
      border: 1px solid var(--border-subtle);
      border-radius: 4px;
    }
    .toc-item.active {
      border-color: var(--accent);
      background: var(--accent-dim);
    }
  }
</style>
