// Mirror of @aiusage/core TOOLS — keep in sync with packages/core/src/types.ts
export const TOOLS = [
  'claude-code',
  'codex',
  'openclaw',
  'opencode',
  'hermes',
  'qoder',
  'cursor',
  'kilocode',
  'kelivo',
  'copilot',
  'gemini',
  'kimi',
  'codebuddy',
  'kiro',
  'grok',
  'antigravity',
  'roocode',
  'zed',
  'goose',
  'omp',
  'pi',
  'craft',
  'droid',
  'zcode',
]
